"""已弃用兼容转发；新代码必须导入对应的 conf、core、lib 或 state 路径。"""

from traning.state import (
    OUTCOME_LOW_SCORE_UPPER,
    OUTCOME_MEDIUM_SCORE_UPPER,
    ArtifactManifest,
    AssociationStatus,
    BeliefState,
    CandidateObservation,
    DataQualityIssue,
    DataQualityReport,
    DataQualitySeverity,
    DataSplit,
    DecisionAction,
    DecisionResult,
    GroundTruthObject,
    InferenceCandidateRecord,
    JSONObject,
    JSONScalar,
    JSONValue,
    ObjectType,
    ObjectTypeDistribution,
    OutcomeCategory,
    OutcomeDistribution,
    OutcomeTrainingSample,
    Point2D,
    RingAttributes,
    RuntimeFrame,
    SliderAttributes,
    SpinnerAttributes,
    TelemetryEvent,
    TrackedObservation,
    TrackLifecycle,
    TrainingCandidateRecord,
    TrainingSample,
    require_transform_fingerprint,
)

__deprecated__ = True

__all__ = [
    "ArtifactManifest",
    "AssociationStatus",
    "BeliefState",
    "CandidateObservation",
    "DataQualityIssue",
    "DataQualityReport",
    "DataQualitySeverity",
    "DataSplit",
    "DecisionAction",
    "DecisionResult",
    "GroundTruthObject",
    "InferenceCandidateRecord",
    "JSONScalar",
    "JSONValue",
    "JSONObject",
    "ObjectType",
    "ObjectTypeDistribution",
    "OUTCOME_LOW_SCORE_UPPER",
    "OUTCOME_MEDIUM_SCORE_UPPER",
    "OutcomeCategory",
    "OutcomeDistribution",
    "OutcomeTrainingSample",
    "Point2D",
    "RingAttributes",
    "RuntimeFrame",
    "SliderAttributes",
    "SpinnerAttributes",
    "TelemetryEvent",
    "TrackedObservation",
    "TrackLifecycle",
    "TrainingCandidateRecord",
    "TrainingSample",
    "require_transform_fingerprint",
]
