"""V2 只读 telemetry 可视化的公开纯投影 API。"""

from .renderers import (
    DashboardEvaluationRow,
    DashboardMetric,
    DashboardMetricRow,
    DashboardSection,
    GalleryTargetOverlay,
    GalleryFrameOverlay,
    GalleryPredictionOverlay,
    QtDashboardModel,
    QtDashboardRenderer,
    QtEvaluationColumn,
    QtEvaluationTableModel,
    QtMetricColumn,
    QtMetricTableModel,
    RichDashboardModel,
    RichDashboardRenderer,
    RichMetricSection,
    build_gallery_frame_overlay,
    project_gallery_target_overlays,
    render_gallery_png,
)

__all__ = (
    "DashboardEvaluationRow",
    "DashboardMetric",
    "DashboardMetricRow",
    "DashboardSection",
    "GalleryTargetOverlay",
    "GalleryFrameOverlay",
    "GalleryPredictionOverlay",
    "QtDashboardModel",
    "QtDashboardRenderer",
    "QtEvaluationColumn",
    "QtEvaluationTableModel",
    "QtMetricColumn",
    "QtMetricTableModel",
    "RichDashboardModel",
    "RichDashboardRenderer",
    "RichMetricSection",
    "build_gallery_frame_overlay",
    "project_gallery_target_overlays",
    "render_gallery_png",
)
