DEFAULT_LANGUAGE = "zh-CN"
DEFAULT_REFRESH_PER_SECOND = 4.0
DEFAULT_PLAIN_INTERVAL_SECONDS = 5.0
DEFAULT_RECENT_EVENT_LIMIT = 12
DEFAULT_WARNING_VRAM_RATIO = 0.9
DEFAULT_CRITICAL_VRAM_RATIO = 0.97
NARROW_TERMINAL_WIDTH = 110
