"""Optimization module facade for scoring, attribution, and parameter search."""

from traning.core.optimization.attribution import (
    ATTRIBUTION_DOMAINS,
    AttributionSummary,
    HardExample,
    analyze_trial_attribution,
)
from traning.core.optimization.parameter_search import (
    ASHAAction,
    ASHAConfig,
    CurriculumGateResult,
    HardExampleSamplingPlan,
    JsonlTrialStore,
    OptimizationPlan,
    OptimizationExecution,
    OptimizationExecutorConfig,
    ParameterSearchConfig,
    SubprojectPassRule,
    TrainingJobSpec,
    TrialHistoryEntry,
    build_hard_example_sampling_plan,
    evaluate_curriculum_gate,
    execute_optimization_plan,
    plan_next_trial,
)
from traning.core.optimization.scoring import (
    AGGREGATE_SCORE_VERSION,
    DEFAULT_CIRCLE_RADIUS_OSU,
    DecisionOutputScoreResult,
    SampleScoreReport,
    SampleScoringInput,
    TrialScoreReport,
    TrialScoreSpec,
    build_batch_gallery_request,
    score_decision_outputs,
    score_sample,
    score_trial,
)

__all__ = [
    "AGGREGATE_SCORE_VERSION",
    "ASHAAction",
    "ASHAConfig",
    "ATTRIBUTION_DOMAINS",
    "AttributionSummary",
    "CurriculumGateResult",
    "DEFAULT_CIRCLE_RADIUS_OSU",
    "DecisionOutputScoreResult",
    "HardExampleSamplingPlan",
    "HardExample",
    "JsonlTrialStore",
    "OptimizationPlan",
    "OptimizationExecution",
    "OptimizationExecutorConfig",
    "ParameterSearchConfig",
    "SampleScoreReport",
    "SampleScoringInput",
    "SubprojectPassRule",
    "TrainingJobSpec",
    "TrialHistoryEntry",
    "TrialScoreReport",
    "TrialScoreSpec",
    "analyze_trial_attribution",
    "build_batch_gallery_request",
    "build_hard_example_sampling_plan",
    "evaluate_curriculum_gate",
    "execute_optimization_plan",
    "plan_next_trial",
    "score_decision_outputs",
    "score_sample",
    "score_trial",
]
